git:
  branch: master

wants:
  mongo: true

secrets:
  - COOKIE_SECRET
  - GROUND_TRUTH_CLIENT_SECRET
env:
  GROUND_TRUTH_CLIENT_ID: 77e4367d4f81acf66b819da4ee8673c89a0fa7b87db6ca5eaaee3b151272f32d
  GROUND_TRUTH_URL: https://login.hack.gt
  ISPRODUCTION: false
